parameters:
#    mind_recherche.example.class: Mind\RechercheBundle\Example

services:
#    mind_recherche.example:
#        class: %mind_recherche.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
