parameters:
    mind_recherche.recherche.class: Mind\RechercheBundle\Recherche

services:
    mind_recherche.recherche:
        class: %mind_recherche.recherche.class%
        arguments: ["@doctrine", "@security.context"]
