<?php

namespace Mind\MpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LuRepository extends EntityRepository
{
    public function findNbConversationNonLu(array $optionsSearch){
    
        $query = $this->_em->createQuery('SELECT COUNT(l)
                                          FROM MindMpBundle:Lu l
                                          WHERE l.idUser = :idUser
                                          AND l.lu = :lu
                                         ');
        
        $query->setParameter('idUser', $optionsSearch['idUser']);
        $query->setParameter('lu', $optionsSearch['lu']);
        
        return $query->getResult();
    }
    
}
