<?php

namespace Mind\MpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessageByIdConversation($idConversation){
        
        $query = $this->_em->createQuery('SELECT m
                                          FROM MindMpBundle:Message m
                                          WHERE m.idConversation = :idConversation
                                         ');
        
        $query->setParameter('idConversation', $idConversation);
        
        return $query->getResult();
    }
}
