<?php

namespace Mind\MpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends EntityRepository
{
    public function findParticipantsByConversation($idConversation, $idUserCourant){
        
        $query = $this->_em->createQuery('SELECT p 
                                          FROM MindMpBundle:Participants p
                                          WHERE p.idConversation = :idConversation
                                          AND p.idUser != :idUserCourant
                                         ');
        
        $query->setParameter('idConversation', $idConversation);
        $query->setParameter('idUserCourant', $idUserCourant);
        
        return $query->getResult();
    }
}
