<?php

namespace Mind\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    
    public function getQuestionsByAuteur($idAuteur){
        
        $query = $this->_em->createQuery('SELECT q
                                          FROM MindSiteBundle:Question q
                                          WHERE q.questionAuteur = :questionAuteur
                                          ORDER BY q.questionDatePublication DESC
                                        ');
        
        $query->setParameter('questionAuteur', $idAuteur);
        
        return $query->getResult();
    }
    
    public function getQuestionsByNbVote(){
        
        $query = $this->_em->createQuery('SELECT q, COUNT(o.idQuestion) AS nbVote
                                          FROM MindSiteBundle:Question q, MindMediaBundle:OpinionQuestion o
                                          WHERE q.id = o.idQuestion
                                          GROUP BY q.id
                                          ORDER BY nbVote ASC
                                          ');
        
        $result = $query->getResult();
        $queryResult = "";
        
        foreach ($result as $unResult){
            unset($unResult['nbVote']);
            $queryResult[] = $unResult[0];
        }
        
        if(empty($queryResult)){
            return $query->getResult();
        }else{
            return $queryResult;
        }
    }
    
    public function getQuestionsByNbCommentaire(){
        
        $query = $this->_em->createQuery('SELECT a, COUNT(c.idQuestion) as nbCom
                                          FROM MindSiteBundle:Question a, MindCommentaireBundle:CommentaireQuestion c
                                          WHERE a.id = c.idQuestion
                                          GROUP BY a.id
                                          ORDER BY nbCom ASC
                                          ');
        
        $result = $query->getResult();
        $queryResult = "";
        
        foreach ($result as $unResult){
            unset($unResult['nbCom']);
            $queryResult[] = $unResult[0];
        }
        
        if(empty($queryResult)){
            return $query->getResult();
        }else{
            return $queryResult;
        }
    }
    
    public function getQuestionsOrderDatePubDesc(){
        
        $query = $this->_em->createQuery('SELECT q
                                         FROM MindSiteBundle:Question q
                                         ORDER BY q.questionDatePublication DESC');
       
        return $query->getResult();
    }
    
    public function getQuestionsOrderDatePubAsc(){
        
        $query = $this->_em->createQuery('SELECT q
                                         FROM MindSiteBundle:Question q
                                         ORDER BY q.questionDatePublication ASC');
       
        return $query->getResult();
    }
    
    public function findQuestionsBySlug($slug){
        
        $query = $this->_em->createQuery('SELECT q
                                         FROM MindSiteBundle:Question q
                                         WHERE q.slug = :slug');
        
        $query->setParameter('slug', $slug);
        
        return $query->getResult();
    }
}
