<?php

namespace Mind\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetQuestionRepository extends EntityRepository
{
}
