<?php

namespace Mind\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetAvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetAvisRepository extends EntityRepository
{
}
