
mind_recherche:
    resource: "@MindRechercheBundle/Resources/config/routing.yml"
    prefix:   /

mind_mp_message:
    resource: "@MindMpBundle/Resources/config/messagerie.yml"
    prefix:   /messagerie

#mind_mp_message:
#    resource: "@MindMpBundle/Resources/config/message.yml"
#    prefix:   /messagerie
#
#mind_mp_conversation:
#    resource: "@MindMpBundle/Resources/config/conversation.yml"
#    prefix:   /messagerie
    
mind_commentaire:
    resource: "@MindCommentaireBundle/Resources/config/routing.yml"
    prefix:   /

mind_media:
    resource: "@MindMediaBundle/Resources/config/routing.yml"
    prefix:   /

mind_site:
    resource: "@MindSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
mind_site_question:
    resource: "@MindSiteBundle/Resources/config/question.yml"
    
mind_site_avis:
    resource: "@MindSiteBundle/Resources/config/avis.yml"
    
mind_site_domaine:
    resource: "@MindSiteBundle/Resources/config/domaines.yml"    
    
#Mind User Admin
mind_user_admin:
  resource: "@MindUserBundle/Resources/config/routing_admin.yml"
  prefix: /admin

#Mind User Compte
mind_user_compte:
    resource: "@MindUserBundle/Resources/config/compte.yml"
    prefix:   /compte
    
mind_user_profile:
    resource: "@MindUserBundle/Resources/config/profile.yml"
    prefix: /profile

# FOS USER BUNDLE ROUTING
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    #prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /compte
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    

#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery

#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media
    
