## YAML Template.

imports:
    - { resource: "@MindMpBundle/Resources/config/services.yml" }
    - { resource: "@MindSiteBundle/Resources/config/services.yml" }
    - { resource: "@MindMediaBundle/Resources/config/services.yml" }