<?php

namespace Mind\CommentaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireQuestionRepository extends EntityRepository
{
    public function getCommentairesByIdQuestion($idQuestion){
        
        $query = $this->_em->createQuery('SELECT c
                                         FROM MindCommentaireBundle:CommentaireQuestion c
                                         WHERE c.idQuestion = :idQuestion');
        
        $query->setParameter('idQuestion', $idQuestion);
        
        return $query->getResult();
    }
    
    public function getNbCommentaireForQuestion($idQuestion){
        
        $query = $this->_em->createQuery('SELECT COUNT(c.idQuestion)
                                          FROM MindCommentaireBundle:CommentaireQuestion c
                                          WHERE c.idQuestion = :idQuestion'
                                        );
        $query->setParameter('idQuestion', $idQuestion);
        
        return $query->getSingleScalarResult();
    }
}
