<?php

namespace Mind\CommentaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireAvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireAvisRepository extends EntityRepository
{
    public function getCommentairesByIdAvis($idAvis){
        
        $query = $this->_em->createQuery('SELECT c
                                         FROM MindCommentaireBundle:CommentaireAvis c
                                         WHERE c.idAvis = :idAvis');
        
        $query->setParameter('idAvis', $idAvis);
        
        return $query->getResult();
    }
    
    public function getNbCommentaireForAvis($idAvis){
        
        $query = $this->_em->createQuery('SELECT COUNT(c.idAvis)
                                          FROM MindCommentaireBundle:CommentaireAvis c
                                          WHERE c.idAvis = :idAvis'
                                        );
        $query->setParameter('idAvis', $idAvis);
        
        return $query->getSingleScalarResult();
    }
}
