## YAML Template.


mind_admin_index:
  pattern: /
  defaults: { _controller: MindUserBundle:Admin:admin }
  
##utilisateurs  
mind_admin_user:
  pattern: /utilisateurs
  defaults: { _controller: MindUserBundle:Admin:users }

mind_admin_update_user_role:
    pattern: /utilisateurs/update-user-role/{idUser}
    defaults: { _controller: MindUserBundle:Admin:UpdateUserRoles }
  
## Domaine  
mind_admin_domaine:
  pattern: /domaines
  defaults: { _controller: MindUserBundle:Domaine:getListeDomaine }
  options:
      expose: true
  
mind_admin_domaine_add:
    pattern: /domaines/ajouter-un-domaine
    defaults: { _controller: MindUserBundle:Domaine:domaines }
    options:
        expose: true

mind_admin_domaine_modifier:
    pattern: /domaines/modifier
    defaults: { _controller: MindUserBundle:Domaine:modifier }
 
mind_admin_domaine_supprimer:
    pattern: /domaine/supprimer/{id}
    defaults: { _controller: MindUserBundle:Domaine:supprimer }
 
mind_admin_domaine_json:
    pattern: /domaines/get-json-data
    defaults: { _controller: MindUserBundle:Domaine:getDataSourceForParent }
    options:
        expose: true

##Avis  
mind_admin_avis:
  pattern: /avis
  defaults: { _controller: MindUserBundle:Admin:avis }
  
##Question  
mind_admin_question:
  pattern: /questions
  defaults: { _controller: MindUserBundle:Admin:questions }
  