<?php

namespace Mind\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpinionQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpinionQuestionRepository extends EntityRepository
{
    public function aDejaVote($idQuestion, $idAuteur){
        
        $query = $this->_em->createQuery('SELECT o
                                          FROM MindMediaBundle:OpinionQuestion o
                                          WHERE o.idQuestion = :idQuestion
                                          AND o.idAuteur = :idAuteur'
                                        );
       
        $query->setParameter('idQuestion', $idQuestion);
        $query->setParameter('idAuteur', $idAuteur);
        
        return $query->getResult();
    }
    
    public function deleteVoteQuestion($idQuestion, $questionAuteur){
        
        $query = $this->_em->createQuery('DELETE MindMediaBundle:OpinionQuestion o
                                         WHERE o.idQuestion = :idQuestion
                                         AND o.idAuteur = :idAuteur ');
        
        $query->setParameter('idQuestion', $idQuestion);
        $query->setParameter('idAuteur', $questionAuteur);
        $query->execute();
    }
    
    public function getOpinionQuestionByIdQuestion($idQuestion, $typeOpinion){
        
        $query = $this->_em->createQuery('SELECT COUNT(o.typeOpinion)
                                          FROM MindMediaBundle:OpinionQuestion o
                                          WHERE o.idQuestion = :idQuestion
                                          AND o.typeOpinion = :typeOpinion');
        $query->setParameter('idQuestion', $idQuestion);
        $query->setParameter('typeOpinion', $typeOpinion);
        
        return $query->getSingleScalarResult();
    }
}
