<?php

namespace Mind\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuivisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuivisRepository extends EntityRepository
{
}
