<?php

namespace Mind\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetSuivisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetSuivisRepository extends EntityRepository
{
}
