<?php

namespace Mind\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteQuestionRepository extends EntityRepository
{
}
