mind_site_homepage:
    pattern:  /
    defaults: { _controller: MindSiteBundle:Site:index }
    
mind_site_get_domaine_ajax:
  pattern: get-domaines-ajax/{id}
  defaults: { _controller: MindSiteBundle:Domaine:getDomainesAjax }
  methods: POST
  
mind_site_domaine_for_form:
  pattern: /get-domaine-form-form
  defaults: { _controller: MindSiteBundle:Domaine:getDomaineForForm }
  options:
      expose: true
  

        
        

