parameters:
    mind_site.avis.class: Mind\SiteBundle\Avis
    mind_site.questions.class: Mind\SiteBundle\Questions
    mind_site.paginator_aware.class: Mind\SiteBundle\PaginatorAware
    mind_site.domaine.class: Mind\SiteBundle\Domaine

services:
  mind_site.date.formatage:
     class: Mind\SiteBundle\DateFormatage
  mind_site.avis:
     class: %mind_site.avis.class%
     arguments: ["@doctrine", "@mind_site.date.formatage", "@router", "@security.context"]
  mind_site.questions:
     class: %mind_site.questions.class%
     arguments: ["@doctrine", "@mind_site.date.formatage", "@router", "@security.context"]
  mind_site.domaine:
     class: %mind_site.domaine.class%
     arguments: ["@doctrine", "@router", "@security.context", "@service_container"]
  mind_site.paginator_aware:
     class: Mind\SiteBundle\PaginatorAware
     arguments: ["@doctrine"]
     tags:
         - {name: knp_paginator.injectable, alias: knp_paginator}
    
        